# Generated by Django 3.0.2 on 2020-01-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Event',
        ),
    ]
